# Uncomment and configure the platforms you use for funding
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [sharpdeveye]
# patreon: 
# open_collective: glazeui
# ko_fi: 
# buy_me_a_coffee: 
# custom: ["https://your-link.com"]
